# Generated by Django 3.0.2 on 2020-01-12 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['connection', 'day', 'number'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='grades',
            name='letter',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ж', 'Ж'), ('З', 'З')], max_length=1, verbose_name='Литера'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='masterteacher',
            field=models.CharField(max_length=80, verbose_name='Классный руководитель'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='classroom',
            field=models.IntegerField(verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Grades', verbose_name='У какого класса урок'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=11, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='end',
            field=models.TimeField(verbose_name='Конец урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='start',
            field=models.TimeField(verbose_name='Начало урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Предмет'),
        ),
    ]
