# Generated by Django 3.0.2 on 2020-01-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(max_length=5000, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=100, verbose_name='Имя ссылки')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['publication_date'],
            },
        ),
    ]
