# Generated by Django 3.0.2 on 2020-01-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Имя ссылки'),
        ),
    ]
