# Generated by Django 3.0.2 on 2020-01-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='subject',
            field=models.CharField(choices=[('Информатика', 'Информатика'), ('История', 'История'), ('Литература', 'Литература'), ('Математика', 'Математика'), ('Обществознание', 'Обществознание'), ('Русский язык', 'Русский язык'), ('Химия и биология', 'Хим-Био'), ('Экономика', 'Экономика'), ('Физика', 'Физика')], max_length=20, verbose_name='Предмет'),
        ),
    ]
