# Generated by Django 3.0.2 on 2020-01-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='fourth',
            field=models.FileField(blank=True, upload_to='min/', verbose_name='Четвертая четверть'),
        ),
        migrations.AddField(
            model_name='grade',
            name='second',
            field=models.FileField(blank=True, upload_to='min/', verbose_name='Вторая четверть'),
        ),
        migrations.AddField(
            model_name='grade',
            name='third',
            field=models.FileField(blank=True, upload_to='min/', verbose_name='Третья четверть'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='first',
            field=models.FileField(blank=True, upload_to='min/', verbose_name='Первая четверть'),
        ),
    ]
