# Generated by Django 3.0.2 on 2020-01-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0002_auto_20200112_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['subj', 'num'], 'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='num',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimum.Subject', verbose_name='Предмет'),
        ),
    ]
